# Generated by Django 3.2 on 2021-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('published_year', models.IntegerField(verbose_name='Год издания')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр книги')),
                ('rating', models.FloatField(verbose_name='Рейтинг книги')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Безопасное удаление книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('books', models.ManyToManyField(to='api.Book')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
